function Area = importfile6060(filename, startRow, endRow)
%IMPORTFILE1 Import numeric data from a text file as column vectors.
%   AREA = IMPORTFILE1(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   AREA = IMPORTFILE1(FILENAME, STARTROW, ENDROW) Reads data from rows
%   STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   Area = importfile1('5microns_6060.txt',11, 2622);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/06/27 09:41:23

%% Initialize variables.
if nargin<=2
    startRow = 11;
    endRow = inf;
end

%% Format string for each line of text:
%   column12: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*91s%11f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', '', 'WhiteSpace', '', 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', '', 'WhiteSpace', '', 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    dataArray{1} = [dataArray{1};dataArrayBlock{1}];
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Area = dataArray{:, 1};


